"""initial_v1_2_schema

Revision ID: d07c490192c5
Revises: 
Create Date: 2026-08-05 09:27:30.840872

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd07c490192c5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('metric_id', sa.String(length=100), nullable=True),
    sa.Column('dimension_key', sa.String(length=200), nullable=True),
    sa.Column('grain', sa.String(length=20), nullable=True),
    sa.Column('operator', sa.String(length=10), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('persistence_periods', sa.Integer(), nullable=False),
    sa.Column('anomaly_sigma', sa.Float(), nullable=True),
    sa.Column('baseline_periods', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('explanation_template', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('fired_count', sa.Integer(), nullable=False),
    sa.Column('actioned_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key')
    )
    op.create_table('areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('parent_area_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('is_own_team', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('context_annotations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_annotations_occurred_on'), ['occurred_on'], unique=False)

    op.create_table('credentials',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('daily_calendar_snapshots',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_meeting_minutes', sa.Integer(), nullable=True),
    sa.Column('meeting_count', sa.Integer(), nullable=True),
    sa.Column('recurring_count', sa.Integer(), nullable=True),
    sa.Column('external_count', sa.Integer(), nullable=True),
    sa.Column('with_agenda_count', sa.Integer(), nullable=True),
    sa.Column('produced_actions_count', sa.Integer(), nullable=True),
    sa.Column('largest_free_block_min', sa.Integer(), nullable=True),
    sa.Column('free_blocks_ge_90min', sa.Integer(), nullable=True),
    sa.Column('available_minutes', sa.Integer(), nullable=True),
    sa.Column('utilization_pct', sa.Float(), nullable=True),
    sa.Column('declined_count', sa.Integer(), nullable=True),
    sa.Column('minutes_by_class', sa.JSON(), nullable=True),
    sa.Column('minutes_by_project', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_date')
    )
    op.create_table('dashboards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('perspective', sa.String(length=50), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('default_filters', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('export_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('export_type', sa.String(length=50), nullable=False),
    sa.Column('dataset_name', sa.String(length=100), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('items_filtered', sa.Integer(), nullable=False),
    sa.Column('items_extracted', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_runs_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_runs_started_at'), ['started_at'], unique=False)

    op.create_table('insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('suggested_actions', sa.JSON(), nullable=True),
    sa.Column('data_caveats', sa.JSON(), nullable=True),
    sa.Column('numeric_guard_passed', sa.Boolean(), nullable=False),
    sa.Column('guard_failures', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('is_suppressed', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insights_period_start'), ['period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_scope'), ['scope'], unique=False)

    op.create_table('manual_metric_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.String(length=100), nullable=False),
    sa.Column('grain', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('dimension_key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('declared_source', sa.String(length=200), nullable=False),
    sa.Column('entered_by', sa.String(length=100), nullable=False),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by'], ['manual_metric_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_definitions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('perspective', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('grain', sa.JSON(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('coverage_basis', sa.String(length=200), nullable=True),
    sa.Column('expected_action', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('data_origin', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('metric_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('metrics_count', sa.Integer(), nullable=True),
    sa.Column('values_written', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.String(length=100), nullable=False),
    sa.Column('grain', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.String(length=100), nullable=False),
    sa.Column('metric_version', sa.Integer(), nullable=False),
    sa.Column('grain', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('dimension_key', sa.String(length=200), nullable=False),
    sa.Column('dimension_value', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('numerator', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('denominator', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('coverage_level', sa.String(length=20), nullable=True),
    sa.Column('is_suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppression_reason', sa.String(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_id', 'metric_version', 'grain', 'period_start', 'dimension_key', name='uq_metric_lookup')
    )
    with op.batch_alter_table('metric_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_values_metric_id'), ['metric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_values_period_start'), ['period_start'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('include_insight', sa.Boolean(), nullable=False),
    sa.Column('formats', sa.JSON(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('source_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('revision_hash', sa.String(), nullable=False),
    sa.Column('author_email', sa.String(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('body_full', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('importance', sa.String(length=50), nullable=True),
    sa.Column('web_link', sa.String(), nullable=True),
    sa.Column('is_redacted', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('filtered_reason', sa.String(), nullable=True),
    sa.Column('blocked_by_safety', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_items_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_processing_status'), ['processing_status'], unique=False)

    op.create_table('sync_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('delta_link', sa.Text(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'resource_id', name='uq_sync_channel_resource')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.String(length=100), nullable=True),
    sa.Column('dimension_key', sa.String(length=200), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('triggered_value', sa.Float(), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_reason', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('decision_id', sa.Uuid(), nullable=True),
    sa.Column('drill_down_query', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('calendar_events',
    sa.Column('source_item_id', sa.Uuid(), nullable=False),
    sa.Column('graph_event_id', sa.String(), nullable=False),
    sa.Column('series_master_id', sa.String(), nullable=True),
    sa.Column('instance_type', sa.String(length=50), nullable=True),
    sa.Column('body_hash', sa.String(length=64), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('join_url', sa.String(), nullable=True),
    sa.Column('linked_chat_id', sa.String(), nullable=True),
    sa.Column('organizer_email', sa.String(), nullable=True),
    sa.Column('my_response', sa.String(length=50), nullable=True),
    sa.Column('show_as', sa.String(length=50), nullable=True),
    sa.Column('sensitivity', sa.String(length=50), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.JSON(), nullable=True),
    sa.Column('attendee_count', sa.Integer(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('meeting_class', sa.String(length=50), nullable=True),
    sa.Column('has_agenda', sa.Boolean(), nullable=False),
    sa.Column('produced_action_items', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('attributed_project_id', sa.Uuid(), nullable=True),
    sa.Column('attributed_area_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_item_id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_join_url'), ['join_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_meeting_class'), ['meeting_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_series_master_id'), ['series_master_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_starts_at'), ['starts_at'], unique=False)

    op.create_table('dashboard_widgets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.String(length=100), nullable=True),
    sa.Column('metric_ids', sa.JSON(), nullable=True),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('grain', sa.String(length=20), nullable=True),
    sa.Column('dimension', sa.String(length=100), nullable=True),
    sa.Column('comparison', sa.String(length=50), nullable=True),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('grid_w', sa.Integer(), nullable=False),
    sa.Column('grid_h', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_widgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_widgets_dashboard_id'), ['dashboard_id'], unique=False)

    op.create_table('report_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('insight_id', sa.Uuid(), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_runs_period_start'), ['period_start'], unique=False)

    op.create_table('saved_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stakeholders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('area_id', sa.Uuid(), nullable=True),
    sa.Column('area_source', sa.String(length=50), nullable=True),
    sa.Column('graph_user_id', sa.String(length=255), nullable=True),
    sa.Column('avg_response_hours', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stakeholders_area_id'), ['area_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('area_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['stakeholders.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_project_snapshots',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tasks_total', sa.Integer(), nullable=True),
    sa.Column('tasks_open', sa.Integer(), nullable=True),
    sa.Column('tasks_in_progress', sa.Integer(), nullable=True),
    sa.Column('tasks_waiting', sa.Integer(), nullable=True),
    sa.Column('tasks_blocked', sa.Integer(), nullable=True),
    sa.Column('tasks_done', sa.Integer(), nullable=True),
    sa.Column('tasks_overdue', sa.Integer(), nullable=True),
    sa.Column('milestones_total', sa.Integer(), nullable=True),
    sa.Column('milestones_at_risk', sa.Integer(), nullable=True),
    sa.Column('milestones_missed', sa.Integer(), nullable=True),
    sa.Column('days_since_activity', sa.Integer(), nullable=True),
    sa.Column('oldest_blocked_days', sa.Integer(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('health_components', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_date', 'project_id')
    )
    op.create_table('decision_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('metric_id', sa.String(length=100), nullable=True),
    sa.Column('metric_snapshot', sa.JSON(), nullable=True),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('insight_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('created_task_ids', sa.JSON(), nullable=True),
    sa.Column('review_due_date', sa.Date(), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('outcome_assessment', sa.String(length=50), nullable=True),
    sa.Column('outcome_metric_snapshot', sa.JSON(), nullable=True),
    sa.Column('outcome_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_log_review_due_date'), ['review_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_log_review_status'), ['review_status'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['stakeholders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_target_date'), ['target_date'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('demand_origin', sa.String(length=50), nullable=True),
    sa.Column('requester_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('waiting_on_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.String(length=50), nullable=True),
    sa.Column('due_date_source', sa.String(length=50), nullable=True),
    sa.Column('original_due_date', sa.String(length=50), nullable=True),
    sa.Column('due_date_change_count', sa.Integer(), nullable=False),
    sa.Column('estimated_effort_minutes', sa.Integer(), nullable=True),
    sa.Column('snooze_until', sa.DateTime(), nullable=True),
    sa.Column('auto_created', sa.Boolean(), nullable=False),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['stakeholders.id'], ),
    sa.ForeignKeyConstraint(['waiting_on_id'], ['stakeholders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_last_interaction_at'), ['last_interaction_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_waiting_on_id'), ['waiting_on_id'], unique=False)

    op.create_table('daily_task_snapshots',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('demand_origin', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('requester_area_id', sa.Uuid(), nullable=True),
    sa.Column('waiting_on_id', sa.Uuid(), nullable=True),
    sa.Column('waiting_on_area_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('original_due_date', sa.Date(), nullable=True),
    sa.Column('age_days', sa.Integer(), nullable=False),
    sa.Column('days_in_status', sa.Integer(), nullable=False),
    sa.Column('cum_days_open', sa.Integer(), nullable=True),
    sa.Column('cum_days_in_progress', sa.Integer(), nullable=True),
    sa.Column('cum_days_waiting', sa.Integer(), nullable=True),
    sa.Column('cum_days_blocked', sa.Integer(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('is_at_risk', sa.Boolean(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('completed_today', sa.Boolean(), nullable=False),
    sa.Column('created_today', sa.Boolean(), nullable=False),
    sa.Column('estimated_effort_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_date', 'task_id')
    )
    with op.batch_alter_table('daily_task_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_task_snapshots_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_task_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_task_snapshots_status'), ['status'], unique=False)

    op.create_table('follow_ups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('target_meeting_id', sa.Uuid(), nullable=True),
    sa.Column('suggested_at', sa.DateTime(), nullable=False),
    sa.Column('draft_subject', sa.String(), nullable=True),
    sa.Column('draft_body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_meeting_id'], ['source_items.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_ups_task_id'), ['task_id'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_item_id', sa.Uuid(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('extraction_conf', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('demand_origin', sa.String(length=50), nullable=True),
    sa.Column('decision_kind', sa.String(length=50), nullable=True),
    sa.Column('decision_conf', sa.Float(), nullable=True),
    sa.Column('resolved_task_id', sa.Uuid(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_signal_type'), ['signal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_source_item_id'), ['source_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_state'), ['state'], unique=False)

    op.create_table('stakeholder_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stakeholder_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('source_item_id', sa.Uuid(), nullable=True),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stakeholder_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stakeholder_interactions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stakeholder_interactions_stakeholder_id'), ['stakeholder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stakeholder_interactions_task_id'), ['task_id'], unique=False)

    op.create_table('task_meeting_links',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('source_item_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_user_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'source_item_id', 'link_type')
    )
    op.create_table('task_stakeholders',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('stakeholder_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'stakeholder_id', 'role')
    )
    op.create_table('correlation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('llm_assessments', sa.JSON(), nullable=True),
    sa.Column('final_decision', sa.String(length=50), nullable=False),
    sa.Column('final_confidence', sa.Float(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('routed_to_triage', sa.Boolean(), nullable=False),
    sa.Column('policy_rule_id', sa.String(length=100), nullable=False),
    sa.Column('guardrail_blocks', sa.JSON(), nullable=True),
    sa.Column('skipped_llm', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correlation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correlation_runs_signal_id'), ['signal_id'], unique=False)

    op.create_table('task_evidences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('source_item_id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_evidences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_evidences_source_item_id'), ['source_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_evidences_task_id'), ['task_id'], unique=False)

    op.create_table('task_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signal_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('target_task_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('candidate_tasks', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_edits', sa.JSON(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_proposals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_proposals_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_proposals_status'), ['status'], unique=False)

    op.create_table('task_status_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('is_undone', sa.Boolean(), nullable=False),
    sa.Column('undone_at', sa.DateTime(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_status_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_status_histories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status_histories_task_id'), ['task_id'], unique=False)

    op.create_table('task_updates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_item_id', sa.Uuid(), nullable=True),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_updates_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_updates_task_id'))

    op.drop_table('task_updates')
    with op.batch_alter_table('task_status_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_status_histories_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_status_histories_created_at'))

    op.drop_table('task_status_histories')
    with op.batch_alter_table('task_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_task_proposals_signal_id'))
        batch_op.drop_index(batch_op.f('ix_task_proposals_created_at'))

    op.drop_table('task_proposals')
    with op.batch_alter_table('task_evidences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_evidences_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_evidences_source_item_id'))

    op.drop_table('task_evidences')
    with op.batch_alter_table('correlation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correlation_runs_signal_id'))

    op.drop_table('correlation_runs')
    op.drop_table('task_stakeholders')
    op.drop_table('task_meeting_links')
    with op.batch_alter_table('stakeholder_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stakeholder_interactions_task_id'))
        batch_op.drop_index(batch_op.f('ix_stakeholder_interactions_stakeholder_id'))
        batch_op.drop_index(batch_op.f('ix_stakeholder_interactions_occurred_at'))

    op.drop_table('stakeholder_interactions')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_state'))
        batch_op.drop_index(batch_op.f('ix_signals_source_item_id'))
        batch_op.drop_index(batch_op.f('ix_signals_signal_type'))
        batch_op.drop_index(batch_op.f('ix_signals_created_at'))

    op.drop_table('signals')
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_ups_task_id'))

    op.drop_table('follow_ups')
    with op.batch_alter_table('daily_task_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_task_snapshots_status'))
        batch_op.drop_index(batch_op.f('ix_daily_task_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_daily_task_snapshots_project_id'))

    op.drop_table('daily_task_snapshots')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_waiting_on_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_last_interaction_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))

    op.drop_table('tasks')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_target_date'))
        batch_op.drop_index(batch_op.f('ix_milestones_status'))

    op.drop_table('milestones')
    with op.batch_alter_table('decision_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_log_review_status'))
        batch_op.drop_index(batch_op.f('ix_decision_log_review_due_date'))

    op.drop_table('decision_log')
    op.drop_table('daily_project_snapshots')
    op.drop_table('projects')
    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stakeholders_area_id'))

    op.drop_table('stakeholders')
    op.drop_table('saved_views')
    with op.batch_alter_table('report_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_runs_period_start'))

    op.drop_table('report_runs')
    with op.batch_alter_table('dashboard_widgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_widgets_dashboard_id'))

    op.drop_table('dashboard_widgets')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_starts_at'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_series_master_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_meeting_class'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_join_url'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_ends_at'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_rule_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    op.drop_table('sync_state')
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_items_processing_status'))
        batch_op.drop_index(batch_op.f('ix_source_items_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_source_items_kind'))
        batch_op.drop_index(batch_op.f('ix_source_items_external_id'))
        batch_op.drop_index(batch_op.f('ix_source_items_conversation_id'))

    op.drop_table('source_items')
    op.drop_table('report_templates')
    op.drop_table('portfolios')
    with op.batch_alter_table('metric_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_values_period_start'))
        batch_op.drop_index(batch_op.f('ix_metric_values_metric_id'))

    op.drop_table('metric_values')
    op.drop_table('metric_targets')
    op.drop_table('metric_runs')
    op.drop_table('metric_definitions')
    op.drop_table('manual_metric_entries')
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insights_scope'))
        batch_op.drop_index(batch_op.f('ix_insights_period_start'))

    op.drop_table('insights')
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_channel'))

    op.drop_table('ingestion_runs')
    op.drop_table('export_runs')
    op.drop_table('dashboards')
    op.drop_table('daily_calendar_snapshots')
    op.drop_table('credentials')
    with op.batch_alter_table('context_annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_annotations_occurred_on'))

    op.drop_table('context_annotations')
    op.drop_table('areas')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
